export const API_RESPONSE = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
      genre_ids: [12, 878, 28],
      id: 299534,
      original_language: 'en',
      original_title: 'Avengers: Endgame',
      overview:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      popularity: 360.041,
      poster_path: '/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
      release_date: '2019-04-24',
      title: 'Avengers: Endgame',
      video: false,
      vote_average: 8.3,
      vote_count: 17587,
    },
    {
      adult: false,
      backdrop_path: '/mmND1cbAilqScI0l5DhoEEQ0h17.jpg',
      genre_ids: [28, 14],
      id: 12211,
      original_language: 'en',
      original_title: 'Highlander: Endgame',
      overview:
        "Immortals Connor and Duncan Macleod join forces against a man from Connor's distant past in the highlands of Scotland, Kell, an immensely powerful immortal who leads an army of equally powerful and deadly immortal swordsmen and assassins. No immortal alive has been able to defeat Kell yet, and neither Connor nor Duncan are skilled enough themselves to take him on and live. The two of them eventually come to one inevitable conclusion; one of them must die so that the combined power of both the Highlanders can bring down Kell for good. There can be only one... the question is, who will it be?",
      popularity: 14.076,
      poster_path: '/agMGPfzc1UJFEYCp6KmhJRuKNkW.jpg',
      release_date: '2000-09-01',
      title: 'Highlander: Endgame',
      video: false,
      vote_average: 4.8,
      vote_count: 256,
    },
    {
      adult: false,
      backdrop_path: '/9fd2eoCgu16WtSAUEDB2rzg2Mmp.jpg',
      genre_ids: [28, 12, 35, 53],
      id: 41135,
      original_language: 'en',
      original_title: 'Operation: Endgame',
      overview:
        'A battle ensues among two government spy teams in an underground facility after their boss is assassinated.',
      popularity: 13.343,
      poster_path: '/ugbGBbzoPQXSgolQVVqRC3NGpIw.jpg',
      release_date: '2010-07-20',
      title: 'Operation: Endgame',
      video: false,
      vote_average: 5,
      vote_count: 136,
    },
    {
      adult: false,
      backdrop_path: '/q3pD0oLk1PF5EFqcAsK2fYagHwj.jpg',
      genre_ids: [80, 18],
      id: 15102,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        "The time is the late '80s, a crucial period in the history of South Africa. President P.W. Botha is hanging on to power by a thread as the African National Congress (ANC) takes up arms against  apartheid and the country tumbles toward insurrection. A British mining concern is convinced that their interests would be better served in a stable South Africa and they quietly dispatch Michael Young, their head of public affairs, to open an unofficial dialogue between the bitter rivals.  Assembling a reluctant yet brilliant team to pave the way to reconciliation by confronting obstacles that initially seem insurmountable, Young places his trust in ANC leader Thabo Mbeki and Afrikaner philosophy professor Willie Esterhuyse. It is their empathy that will ultimately serve as the catalyst for change by proving more powerful than the terrorist bombs that threaten to disrupt the peaceful dialogue.",
      popularity: 8.084,
      poster_path: '/b8WzwCABwVRVdw14OcE6pmezJjK.jpg',
      release_date: '2009-01-18',
      title: 'Endgame',
      video: false,
      vote_average: 5.8,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: '/kd95nBirBiMK5AjMlrB2eqIY7HA.jpg',
      genre_ids: [18],
      id: 376651,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        "Since he was 5 yrs old, Jose's abuelita taught him to play chess like his grandfather who was a champion in Mexico. Now as part of the Brownsville school team, Jose has the chance to use his skills and for once in his life, finds himself in the spotlight, as he tries to help his team make it to the Texas state finals. As their coach, Mr. Alvarado, teaches his students the meaning of perseverance and team effort in the face of adversity, Jose discovers his own strengths and uses them to bring his broken family together.",
      popularity: 9.278,
      poster_path: '/bx2qO3rfiOL6LXtbWlTDzFNQEcZ.jpg',
      release_date: '2015-09-25',
      title: 'Endgame',
      video: false,
      vote_average: 6,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/oDvkt6sbGBLXt6EfPgl5ozoIb2f.jpg',
      genre_ids: [28, 27],
      id: 400605,
      original_language: 'en',
      original_title: 'Dead Rising: Endgame',
      overview:
        'Investigative reporter Chase Carter must stop a secret government conspiracy in the zombie infested quarantine zone of East Mission City.',
      popularity: 11.38,
      poster_path: '/yQZCTiMWnXNTeKtnBAOmGdUT0rf.jpg',
      release_date: '2016-06-20',
      title: 'Dead Rising: Endgame',
      video: false,
      vote_average: 5.1,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: '/9ZscJdBhYb5RWBG0qsJD3Cy07oH.jpg',
      genre_ids: [80, 18, 53],
      id: 51491,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        "Sex is currency. It commands power and can instill fear. Tom, a young man with a troubled past finds himself sucked into a seedy underworld by George Norris, a now super villain with a sadistic streak. A helpless pawn in one of Norris's narcotic scams with a bent cop, Dunston, Tom is dragged deeper into a vicious circle of blood money, vice and ruthless violence from which their seems no way out. Until fate gives Tom a glimmer of hope. When Norris is killed in his apartment, Tom seizes his chance to escape. Terrified and covered in Norris's blood, Tom heads downstairs to his neighbors, Max and Nikki his new friends in the city. With going to the police out of the question, Max and Nikki speed Tom to their desolate cottage deep in the Welsh countryside. With the luxury of space, Tom begins to realize a long-forgotten dream; a return to happier times before his innocence was shattered. Suppressed emotion flood back provoked by Tom's attraction to Nikki...",
      popularity: 6.586,
      poster_path: '/zHbtfCHvSeZbogq3Iv0vNYxDnkb.jpg',
      release_date: '2001-01-01',
      title: 'Endgame',
      video: false,
      vote_average: 4.9,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [27],
      id: 353227,
      original_language: 'en',
      original_title: 'Horror 102: Endgame',
      overview:
        "A group of high school/university students are staying in an abandoned insane asylum  as part of a school project field trip, which turns out to be haunted by the tormented spirits of it's previous inhabitants.",
      popularity: 5.666,
      poster_path: '/5jLa9Qgv642unRBbiT9NAWKWTK4.jpg',
      release_date: '2004-09-04',
      title: 'Horror 102: Endgame',
      video: false,
      vote_average: 1,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878],
      id: 28850,
      original_language: 'it',
      original_title: 'Endgame - Bronx lotta finale',
      overview:
        'In the year 2025, a nuclear holocaust has left New York City an irradiated, but not abandoned, wasteland. The ruined city is inhabited now by scavenger packs and telepathic mutants, who are persecuted by the elite survivors. Keeping the people pacified is the reality television program Endgame, where hunters and gladiators fight to the death.',
      popularity: 2.321,
      poster_path: '/vm3Vyng17XlQEgmEQlWKBMzzGPv.jpg',
      release_date: '1983-11-05',
      title: 'Endgame',
      video: false,
      vote_average: 5.3,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18, 10770],
      id: 68139,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        'Hamm is blind and unable to stand; Clov, his servant, is unable to sit; Nagg and Nell are his father and mother, who are legless and live in dustbins. Together they live in a room with two windows, but there may be nothing at all outside.',
      popularity: 2.433,
      poster_path: '/s2HzASBTwqD9sVtpx15WJVnTAIX.jpg',
      release_date: '2000-09-10',
      title: 'Endgame',
      video: false,
      vote_average: 6.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/vScBqbDYn95Az8SvNoYKGvFFVmy.jpg',
      genre_ids: [99],
      id: 720914,
      original_language: 'en',
      original_title: 'Endgame 2050',
      overview:
        'What will the future be like in the year 2050? Endgame 2050 is a feature-length documentary that gives us a glimpse into that future, and it does not look good. Featuring musician Moby along with leading scientists, and created by physician turned environmentalist Sofia Pineda Ochoa, Endgame 2050 is an urgent call to action to tackle the existential crises bearing down on the planet.',
      popularity: 3.206,
      poster_path: '/zcGm1iSkR4p6YawvFpJx04JfHOX.jpg',
      release_date: '2020-05-19',
      title: 'Endgame 2050',
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/8ac7F60WvgdOSJ3c5TptoaHeIFd.jpg',
      genre_ids: [99],
      id: 18312,
      original_language: 'en',
      original_title: 'Endgame: Blueprint for Global Enslavement',
      overview:
        "For the New World Order (NWO), a world government is just the beginning. Once in place they can engage their plan to exterminate 80% of the world's population, while enabling the 'elites' to live forever with the aid of advanced technology. For the first time, crusading filmmaker Alex Jones reveals their secret plan for humanity's extermination: Operation Endgame.",
      popularity: 7.402,
      poster_path: '/l8t0Z8y0fhSVChzbUf9TOfNh5R7.jpg',
      release_date: '2007-11-01',
      title: 'Endgame: Blueprint for Global Enslavement',
      video: true,
      vote_average: 7.1,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 320200,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        'An ordinary chess game between a man and a woman turns into a battle of the sexes.',
      popularity: 1.4,
      poster_path: null,
      release_date: '1999-12-01',
      title: 'Endgame',
      video: false,
      vote_average: 7,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 233407,
      original_language: 'en',
      original_title: 'Endgame',
      overview: "An adaptation of Samuel Beckett's play.",
      popularity: 0.897,
      poster_path: '/thMNnM22Uk1BVg0MHsL42sd3LJN.jpg',
      release_date: '1989-01-01',
      title: 'Endgame',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/igO0gR0KyGv4LtU4xTOx1TBMaFM.jpg',
      genre_ids: [],
      id: 691329,
      original_language: 'en',
      original_title: 'Endgame & Rough for Theatre II',
      overview:
        'Hamm is an ageing, blind tyrant who is confined to a wheelchair – but soon becomes locked in a bleakly funny and subversively devastating stalemate.  Endgame forms the first half of a double bill, performed alongside Samuel Beckett’s rarely-seen short play Rough for Theatre II.',
      popularity: 2.319,
      poster_path: '/aCsEmMynu4jHN91zSom8z1muxTV.jpg',
      release_date: '2020-04-01',
      title: 'Endgame & Rough for Theatre II',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 401828,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        'After a tough week at the office, Richard and George like to play war games over the weekend to relax. The dispassionate atmosphere and minimalistic style with which the growing brutality is handled slowly wipes the smile from your face, before making sure that it doesn’t return.',
      popularity: 0.6,
      poster_path: '/jntVd28HefooS3ykVMADPAWgY8Q.jpg',
      release_date: '2015-01-01',
      title: 'Endgame',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 756793,
      original_language: 'en',
      original_title: 'Endgame',
      overview:
        "A Father's cautionary tale about internet safety turns sinister when the lines between truth and fiction are blurred.",
      popularity: 0.6,
      poster_path: '/8xSSFMas5hx0oyz6NWGTxqMcCBi.jpg',
      release_date: '2020-12-01',
      title: 'Endgame',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99, 10402],
      id: 545817,
      original_language: 'en',
      original_title: "Britten's Endgame",
      overview:
        "To mark the centenary of Benjamin Britten's birth, Britten’s Endgame explores the composer's creativity in the face of death.  Those closest to him watched anxiously as he raced to complete his final opera, Death in Venice, in defiance of medical advice, tackling an edgy subject with many resonances in his own life.  His eventual heart operation left him incapacitated and prematurely old and frail, yet somehow he rediscovered his creative urge to produce two late masterpieces. This is a rich and poignant film about Britten’s final years, and the impact of what Peter Pears called 'an evil opera'.",
      popularity: 0.6,
      poster_path: '/j94qqELDTsOxYxXZOpNKYWhwzdh.jpg',
      release_date: '2015-01-01',
      title: "Britten's Endgame",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [27, 53],
      id: 756462,
      original_language: 'en',
      original_title: 'Halloween Endgame',
      overview:
        'Set One Year Later After Halloween The Hunt (2020)... John and the infamous Michael Myers reunite one last time.',
      popularity: 0.851,
      poster_path: '/6CCVGjjQUG7E69sOmRjeO4fenWR.jpg',
      release_date: '2021-01-01',
      title: 'Halloween Endgame',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/oJk602G6mEnhuyEOvUroCQIXASi.jpg',
      genre_ids: [28, 12, 18, 878],
      id: 718185,
      original_language: 'en',
      original_title: 'BCTV: Endgame',
      overview:
        'The Bishop Carroll TV Broadcasting class faces its most dangerous challenge yet when their new broadcast is completely erased. The senior Class of 2020 takes the reigns to save the broadcast, but in the process faces a dangerous journey through time and must reflect on the unavoidable and emotional end of their high school career.',
      popularity: 0.6,
      poster_path: '/sKnjNsZ2AKYHOSxKgjIaBKAqOTk.jpg',
      release_date: '2020-07-10',
      title: 'BCTV: Endgame',
      video: false,
      vote_average: 6,
      vote_count: 2,
    },
  ],
  total_pages: 2,
  total_results: 24,
};

export const GENRE_RESPONSE = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
];
