export const COUNTRY_LIST = [
  { name: 'Afghanistan', alpha_code: 'AFG', country_code: '004' },
  { name: 'Åland Islands', alpha_code: 'ALA', country_code: '248' },
  { name: 'Albania', alpha_code: 'ALB', country_code: '008' },
  { name: 'Algeria', alpha_code: 'DZA', country_code: '012' },
  { name: 'American Samoa', alpha_code: 'ASM', country_code: '016' },
  { name: 'Andorra', alpha_code: 'AND', country_code: '020' },
  { name: 'Angola', alpha_code: 'AGO', country_code: '024' },
  { name: 'Anguilla', alpha_code: 'AIA', country_code: '660' },
  { name: 'Antarctica', alpha_code: 'ATA', country_code: '010' },
  { name: 'Antigua and Barbuda', alpha_code: 'ATG', country_code: '028' },
  { name: 'Argentina', alpha_code: 'ARG', country_code: '032' },
  { name: 'Armenia', alpha_code: 'ARM', country_code: '051' },
  { name: 'Aruba', alpha_code: 'ABW', country_code: '533' },
  { name: 'Australia', alpha_code: 'AUS', country_code: '036' },
  { name: 'Austria', alpha_code: 'AUT', country_code: '040' },
  { name: 'Azerbaijan', alpha_code: 'AZE', country_code: '031' },
  { name: 'Bahamas', alpha_code: 'BHS', country_code: '044' },
  { name: 'Bahrain', alpha_code: 'BHR', country_code: '048' },
  { name: 'Bangladesh', alpha_code: 'BGD', country_code: '050' },
  { name: 'Barbados', alpha_code: 'BRB', country_code: '052' },
  { name: 'Belarus', alpha_code: 'BLR', country_code: '112' },
  { name: 'Belgium', alpha_code: 'BEL', country_code: '056' },
  { name: 'Belize', alpha_code: 'BLZ', country_code: '084' },
  { name: 'Benin', alpha_code: 'BEN', country_code: '204' },
  { name: 'Bermuda', alpha_code: 'BMU', country_code: '060' },
  { name: 'Bhutan', alpha_code: 'BTN', country_code: '064' },
  {
    name: 'Bolivia (Plurinational State of)',
    alpha_code: 'BOL',
    country_code: '068',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alpha_code: 'BES',
    country_code: '535',
  },
  { name: 'Bosnia and Herzegovina', alpha_code: 'BIH', country_code: '070' },
  { name: 'Botswana', alpha_code: 'BWA', country_code: '072' },
  { name: 'Bouvet Island', alpha_code: 'BVT', country_code: '074' },
  { name: 'Brazil', alpha_code: 'BRA', country_code: '076' },
  {
    name: 'British Indian Ocean Territory',
    alpha_code: 'IOT',
    country_code: '086',
  },
  { name: 'Brunei Darussalam', alpha_code: 'BRN', country_code: '096' },
  { name: 'Bulgaria', alpha_code: 'BGR', country_code: '100' },
  { name: 'Burkina Faso', alpha_code: 'BFA', country_code: '854' },
  { name: 'Burundi', alpha_code: 'BDI', country_code: '108' },
  { name: 'Cabo Verde', alpha_code: 'CPV', country_code: '132' },
  { name: 'Cambodia', alpha_code: 'KHM', country_code: '116' },
  { name: 'Cameroon', alpha_code: 'CMR', country_code: '120' },
  { name: 'Canada', alpha_code: 'CAN', country_code: '124' },
  { name: 'Cayman Islands', alpha_code: 'CYM', country_code: '136' },
  { name: 'Central African Republic', alpha_code: 'CAF', country_code: '140' },
  { name: 'Chad', alpha_code: 'TCD', country_code: '148' },
  { name: 'Chile', alpha_code: 'CHL', country_code: '152' },
  { name: 'China', alpha_code: 'CHN', country_code: '156' },
  { name: 'Christmas Island', alpha_code: 'CXR', country_code: '162' },
  { name: 'Cocos (Keeling) Islands', alpha_code: 'CCK', country_code: '166' },
  { name: 'Colombia', alpha_code: 'COL', country_code: '170' },
  { name: 'Comoros', alpha_code: 'COM', country_code: '174' },
  { name: 'Congo', alpha_code: 'COG', country_code: '178' },
  {
    name: 'Congo, Democratic Republic of the',
    alpha_code: 'COD',
    country_code: '180',
  },
  { name: 'Cook Islands', alpha_code: 'COK', country_code: '184' },
  { name: 'Costa Rica', alpha_code: 'CRI', country_code: '188' },
  { name: "Côte d'Ivoire", alpha_code: 'CIV', country_code: '384' },
  { name: 'Croatia', alpha_code: 'HRV', country_code: '191' },
  { name: 'Cuba', alpha_code: 'CUB', country_code: '192' },
  { name: 'Curaçao', alpha_code: 'CUW', country_code: '531' },
  { name: 'Cyprus', alpha_code: 'CYP', country_code: '196' },
  { name: 'Czechia', alpha_code: 'CZE', country_code: '203' },
  { name: 'Denmark', alpha_code: 'DNK', country_code: '208' },
  { name: 'Djibouti', alpha_code: 'DJI', country_code: '262' },
  { name: 'Dominica', alpha_code: 'DMA', country_code: '212' },
  { name: 'Dominican Republic', alpha_code: 'DOM', country_code: '214' },
  { name: 'Ecuador', alpha_code: 'ECU', country_code: '218' },
  { name: 'Egypt', alpha_code: 'EGY', country_code: '818' },
  { name: 'El Salvador', alpha_code: 'SLV', country_code: '222' },
  { name: 'Equatorial Guinea', alpha_code: 'GNQ', country_code: '226' },
  { name: 'Eritrea', alpha_code: 'ERI', country_code: '232' },
  { name: 'Estonia', alpha_code: 'EST', country_code: '233' },
  { name: 'Eswatini', alpha_code: 'SWZ', country_code: '748' },
  { name: 'Ethiopia', alpha_code: 'ETH', country_code: '231' },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha_code: 'FLK',
    country_code: '238',
  },
  { name: 'Faroe Islands', alpha_code: 'FRO', country_code: '234' },
  { name: 'Fiji', alpha_code: 'FJI', country_code: '242' },
  { name: 'Finland', alpha_code: 'FIN', country_code: '246' },
  { name: 'France', alpha_code: 'FRA', country_code: '250' },
  { name: 'French Guiana', alpha_code: 'GUF', country_code: '254' },
  { name: 'French Polynesia', alpha_code: 'PYF', country_code: '258' },
  {
    name: 'French Southern Territories',
    alpha_code: 'ATF',
    country_code: '260',
  },
  { name: 'Gabon', alpha_code: 'GAB', country_code: '266' },
  { name: 'Gambia', alpha_code: 'GMB', country_code: '270' },
  { name: 'Georgia', alpha_code: 'GEO', country_code: '268' },
  { name: 'Germany', alpha_code: 'DEU', country_code: '276' },
  { name: 'Ghana', alpha_code: 'GHA', country_code: '288' },
  { name: 'Gibraltar', alpha_code: 'GIB', country_code: '292' },
  { name: 'Greece', alpha_code: 'GRC', country_code: '300' },
  { name: 'Greenland', alpha_code: 'GRL', country_code: '304' },
  { name: 'Grenada', alpha_code: 'GRD', country_code: '308' },
  { name: 'Guadeloupe', alpha_code: 'GLP', country_code: '312' },
  { name: 'Guam', alpha_code: 'GUM', country_code: '316' },
  { name: 'Guatemala', alpha_code: 'GTM', country_code: '320' },
  { name: 'Guernsey', alpha_code: 'GGY', country_code: '831' },
  { name: 'Guinea', alpha_code: 'GIN', country_code: '324' },
  { name: 'Guinea-Bissau', alpha_code: 'GNB', country_code: '624' },
  { name: 'Guyana', alpha_code: 'GUY', country_code: '328' },
  { name: 'Haiti', alpha_code: 'HTI', country_code: '332' },
  {
    name: 'Heard Island and McDonald Islands',
    alpha_code: 'HMD',
    country_code: '334',
  },
  { name: 'Holy See', alpha_code: 'VAT', country_code: '336' },
  { name: 'Honduras', alpha_code: 'HND', country_code: '340' },
  { name: 'Hong Kong', alpha_code: 'HKG', country_code: '344' },
  { name: 'Hungary', alpha_code: 'HUN', country_code: '348' },
  { name: 'Iceland', alpha_code: 'ISL', country_code: '352' },
  { name: 'India', alpha_code: 'IND', country_code: '356' },
  { name: 'Indonesia', alpha_code: 'IDN', country_code: '360' },
  {
    name: 'Iran (Islamic Republic of)',
    alpha_code: 'IRN',
    country_code: '364',
  },
  { name: 'Iraq', alpha_code: 'IRQ', country_code: '368' },
  { name: 'Ireland', alpha_code: 'IRL', country_code: '372' },
  { name: 'Isle of Man', alpha_code: 'IMN', country_code: '833' },
  { name: 'Israel', alpha_code: 'ISR', country_code: '376' },
  { name: 'Italy', alpha_code: 'ITA', country_code: '380' },
  { name: 'Jamaica', alpha_code: 'JAM', country_code: '388' },
  { name: 'Japan', alpha_code: 'JPN', country_code: '392' },
  { name: 'Jersey', alpha_code: 'JEY', country_code: '832' },
  { name: 'Jordan', alpha_code: 'JOR', country_code: '400' },
  { name: 'Kazakhstan', alpha_code: 'KAZ', country_code: '398' },
  { name: 'Kenya', alpha_code: 'KEN', country_code: '404' },
  { name: 'Kiribati', alpha_code: 'KIR', country_code: '296' },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha_code: 'PRK',
    country_code: '408',
  },
  { name: 'Korea, Republic of', alpha_code: 'KOR', country_code: '410' },
  { name: 'Kuwait', alpha_code: 'KWT', country_code: '414' },
  { name: 'Kyrgyzstan', alpha_code: 'KGZ', country_code: '417' },
  {
    name: "Lao People's Democratic Republic",
    alpha_code: 'LAO',
    country_code: '418',
  },
  { name: 'Latvia', alpha_code: 'LVA', country_code: '428' },
  { name: 'Lebanon', alpha_code: 'LBN', country_code: '422' },
  { name: 'Lesotho', alpha_code: 'LSO', country_code: '426' },
  { name: 'Liberia', alpha_code: 'LBR', country_code: '430' },
  { name: 'Libya', alpha_code: 'LBY', country_code: '434' },
  { name: 'Liechtenstein', alpha_code: 'LIE', country_code: '438' },
  { name: 'Lithuania', alpha_code: 'LTU', country_code: '440' },
  { name: 'Luxembourg', alpha_code: 'LUX', country_code: '442' },
  { name: 'Macao', alpha_code: 'MAC', country_code: '446' },
  { name: 'Madagascar', alpha_code: 'MDG', country_code: '450' },
  { name: 'Malawi', alpha_code: 'MWI', country_code: '454' },
  { name: 'Malaysia', alpha_code: 'MYS', country_code: '458' },
  { name: 'Maldives', alpha_code: 'MDV', country_code: '462' },
  { name: 'Mali', alpha_code: 'MLI', country_code: '466' },
  { name: 'Malta', alpha_code: 'MLT', country_code: '470' },
  { name: 'Marshall Islands', alpha_code: 'MHL', country_code: '584' },
  { name: 'Martinique', alpha_code: 'MTQ', country_code: '474' },
  { name: 'Mauritania', alpha_code: 'MRT', country_code: '478' },
  { name: 'Mauritius', alpha_code: 'MUS', country_code: '480' },
  { name: 'Mayotte', alpha_code: 'MYT', country_code: '175' },
  { name: 'Mexico', alpha_code: 'MEX', country_code: '484' },
  {
    name: 'Micronesia (Federated States of)',
    alpha_code: 'FSM',
    country_code: '583',
  },
  { name: 'Moldova, Republic of', alpha_code: 'MDA', country_code: '498' },
  { name: 'Monaco', alpha_code: 'MCO', country_code: '492' },
  { name: 'Mongolia', alpha_code: 'MNG', country_code: '496' },
  { name: 'Montenegro', alpha_code: 'MNE', country_code: '499' },
  { name: 'Montserrat', alpha_code: 'MSR', country_code: '500' },
  { name: 'Morocco', alpha_code: 'MAR', country_code: '504' },
  { name: 'Mozambique', alpha_code: 'MOZ', country_code: '508' },
  { name: 'Myanmar', alpha_code: 'MMR', country_code: '104' },
  { name: 'Namibia', alpha_code: 'NAM', country_code: '516' },
  { name: 'Nauru', alpha_code: 'NRU', country_code: '520' },
  { name: 'Nepal', alpha_code: 'NPL', country_code: '524' },
  { name: 'Netherlands', alpha_code: 'NLD', country_code: '528' },
  { name: 'New Caledonia', alpha_code: 'NCL', country_code: '540' },
  { name: 'New Zealand', alpha_code: 'NZL', country_code: '554' },
  { name: 'Nicaragua', alpha_code: 'NIC', country_code: '558' },
  { name: 'Niger', alpha_code: 'NER', country_code: '562' },
  { name: 'Nigeria', alpha_code: 'NGA', country_code: '566' },
  { name: 'Niue', alpha_code: 'NIU', country_code: '570' },
  { name: 'Norfolk Island', alpha_code: 'NFK', country_code: '574' },
  { name: 'North Macedonia', alpha_code: 'MKD', country_code: '807' },
  { name: 'Northern Mariana Islands', alpha_code: 'MNP', country_code: '580' },
  { name: 'Norway', alpha_code: 'NOR', country_code: '578' },
  { name: 'Oman', alpha_code: 'OMN', country_code: '512' },
  { name: 'Pakistan', alpha_code: 'PAK', country_code: '586' },
  { name: 'Palau', alpha_code: 'PLW', country_code: '585' },
  { name: 'Palestine, State of', alpha_code: 'PSE', country_code: '275' },
  { name: 'Panama', alpha_code: 'PAN', country_code: '591' },
  { name: 'Papua New Guinea', alpha_code: 'PNG', country_code: '598' },
  { name: 'Paraguay', alpha_code: 'PRY', country_code: '600' },
  { name: 'Peru', alpha_code: 'PER', country_code: '604' },
  { name: 'Philippines', alpha_code: 'PHL', country_code: '608' },
  { name: 'Pitcairn', alpha_code: 'PCN', country_code: '612' },
  { name: 'Poland', alpha_code: 'POL', country_code: '616' },
  { name: 'Portugal', alpha_code: 'PRT', country_code: '620' },
  { name: 'Puerto Rico', alpha_code: 'PRI', country_code: '630' },
  { name: 'Qatar', alpha_code: 'QAT', country_code: '634' },
  { name: 'Réunion', alpha_code: 'REU', country_code: '638' },
  { name: 'Romania', alpha_code: 'ROU', country_code: '642' },
  { name: 'Russian Federation', alpha_code: 'RUS', country_code: '643' },
  { name: 'Rwanda', alpha_code: 'RWA', country_code: '646' },
  { name: 'Saint Barthélemy', alpha_code: 'BLM', country_code: '652' },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha_code: 'SHN',
    country_code: '654',
  },
  { name: 'Saint Kitts and Nevis', alpha_code: 'KNA', country_code: '659' },
  { name: 'Saint Lucia', alpha_code: 'LCA', country_code: '662' },
  {
    name: 'Saint Martin (French part)',
    alpha_code: 'MAF',
    country_code: '663',
  },
  { name: 'Saint Pierre and Miquelon', alpha_code: 'SPM', country_code: '666' },
  {
    name: 'Saint Vincent and the Grenadines',
    alpha_code: 'VCT',
    country_code: '670',
  },
  { name: 'Samoa', alpha_code: 'WSM', country_code: '882' },
  { name: 'San Marino', alpha_code: 'SMR', country_code: '674' },
  { name: 'Sao Tome and Principe', alpha_code: 'STP', country_code: '678' },
  { name: 'Saudi Arabia', alpha_code: 'SAU', country_code: '682' },
  { name: 'Senegal', alpha_code: 'SEN', country_code: '686' },
  { name: 'Serbia', alpha_code: 'SRB', country_code: '688' },
  { name: 'Seychelles', alpha_code: 'SYC', country_code: '690' },
  { name: 'Sierra Leone', alpha_code: 'SLE', country_code: '694' },
  { name: 'Singapore', alpha_code: 'SGP', country_code: '702' },
  { name: 'Sint Maarten (Dutch part)', alpha_code: 'SXM', country_code: '534' },
  { name: 'Slovakia', alpha_code: 'SVK', country_code: '703' },
  { name: 'Slovenia', alpha_code: 'SVN', country_code: '705' },
  { name: 'Solomon Islands', alpha_code: 'SLB', country_code: '090' },
  { name: 'Somalia', alpha_code: 'SOM', country_code: '706' },
  { name: 'South Africa', alpha_code: 'ZAF', country_code: '710' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alpha_code: 'SGS',
    country_code: '239',
  },
  { name: 'South Sudan', alpha_code: 'SSD', country_code: '728' },
  { name: 'Spain', alpha_code: 'ESP', country_code: '724' },
  { name: 'Sri Lanka', alpha_code: 'LKA', country_code: '144' },
  { name: 'Sudan', alpha_code: 'SDN', country_code: '729' },
  { name: 'Suriname', alpha_code: 'SUR', country_code: '740' },
  { name: 'Svalbard and Jan Mayen', alpha_code: 'SJM', country_code: '744' },
  { name: 'Sweden', alpha_code: 'SWE', country_code: '752' },
  { name: 'Switzerland', alpha_code: 'CHE', country_code: '756' },
  { name: 'Syrian Arab Republic', alpha_code: 'SYR', country_code: '760' },
  { name: 'Taiwan, Province of China', alpha_code: 'TWN', country_code: '158' },
  { name: 'Tajikistan', alpha_code: 'TJK', country_code: '762' },
  {
    name: 'Tanzania, United Republic of',
    alpha_code: 'TZA',
    country_code: '834',
  },
  { name: 'Thailand', alpha_code: 'THA', country_code: '764' },
  { name: 'Timor-Leste', alpha_code: 'TLS', country_code: '626' },
  { name: 'Togo', alpha_code: 'TGO', country_code: '768' },
  { name: 'Tokelau', alpha_code: 'TKL', country_code: '772' },
  { name: 'Tonga', alpha_code: 'TON', country_code: '776' },
  { name: 'Trinidad and Tobago', alpha_code: 'TTO', country_code: '780' },
  { name: 'Tunisia', alpha_code: 'TUN', country_code: '788' },
  { name: 'Turkey', alpha_code: 'TUR', country_code: '792' },
  { name: 'Turkmenistan', alpha_code: 'TKM', country_code: '795' },
  { name: 'Turks and Caicos Islands', alpha_code: 'TCA', country_code: '796' },
  { name: 'Tuvalu', alpha_code: 'TUV', country_code: '798' },
  { name: 'Uganda', alpha_code: 'UGA', country_code: '800' },
  { name: 'Ukraine', alpha_code: 'UKR', country_code: '804' },
  { name: 'United Arab Emirates', alpha_code: 'ARE', country_code: '784' },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alpha_code: 'GBR',
    country_code: '826',
  },
  { name: 'United States of America', alpha_code: 'USA', country_code: '840' },
  {
    name: 'United States Minor Outlying Islands',
    alpha_code: 'UMI',
    country_code: '581',
  },
  { name: 'Uruguay', alpha_code: 'URY', country_code: '858' },
  { name: 'Uzbekistan', alpha_code: 'UZB', country_code: '860' },
  { name: 'Vanuatu', alpha_code: 'VUT', country_code: '548' },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alpha_code: 'VEN',
    country_code: '862',
  },
  { name: 'Viet Nam', alpha_code: 'VNM', country_code: '704' },
  { name: 'Virgin Islands (British)', alpha_code: 'VGB', country_code: '092' },
  { name: 'Virgin Islands (U.S.)', alpha_code: 'VIR', country_code: '850' },
  { name: 'Wallis and Futuna', alpha_code: 'WLF', country_code: '876' },
  { name: 'Western Sahara', alpha_code: 'ESH', country_code: '732' },
  { name: 'Yemen', alpha_code: 'YEM', country_code: '887' },
  { name: 'Zambia', alpha_code: 'ZMB', country_code: '894' },
  { name: 'Zimbabwe', alpha_code: 'ZWE', country_code: '716' },
];
